name: deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 103.23.60.90
          port: 2222
          username: ismael
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd /var/www/html/raddut; git pull origin master;php artisan route:cache;php artisan view:cache; npm run build;sudo service php8.2-fpm reload"
